name: Generate ASCII

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List files
              run: ls -ltra  
            
            - name: Excute script to install cowsay
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dragon-text-file
                path: dragon.txt

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                name: dragon-text-file
                    
            - name: Test file exists
              run: grep -i "dragon" dragon.txt
