name: Generate ASCII

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List files
              run: ls -ltra  
            
            - name: Excute script to install cowsay
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh

    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10s
              run: sleep 10  
                    
            - name: Test file exists
              run: grep -i "dragon" dragon.txt
