name: Generate ASCII

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List files
              uses: ls -ltra  

            - name: Excute script to install cowsay
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh
