name: Generate ASCII

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Insatall cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay command
              run: cowsay -f dragon "Run for cover, I feel a sneeze coming on." >> dragon.txt

            - name: Test file exists
              run: grep -i "dragon" dragon.txt
              
            - name: List files
              run: ls -ltra  